[project]
name = "transformer-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "mohd-khan-01", email = "rayyans.pf@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "torch>=2.14.0",
]

[project.scripts]
transformer-from-scratch = "transformer_from_scratch:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
